<?php
/**
 * @package WordPress
 * @subpackage Adamantium - Starter Kit
 * @author Alan Gabriel Dawidowicz - www.alandawi.com.ar
 */

	/*
		If you do not know what you do, DO NOT EDIT THIS FILE
	*/

	define("THEME_DIR", get_template_directory_uri());


	// THEME OPTIONS
	/* How it works: http://wptheming.com/options-framework-plugin/ */
	/* If you are not using Theme Options can comment this lines */
	if ( !function_exists( 'optionsframework_init' ) ) {
		define( 'OPTIONS_FRAMEWORK_DIRECTORY', get_bloginfo('template_directory') . '/admin/' );
		require_once dirname( __FILE__ ) . '/admin/options-framework.php';
	}


	// ADAMANTIUM CORE
	/* Do not delete this line! */
	require (TEMPLATEPATH . '/includes/adamantium.php');
	

	// CUSTOM POST TYPES
	/* If you are not using Custom Post Types can comment this line */
	require (TEMPLATEPATH . '/includes/custom-post-types.php'); 


	// SHORTCODES
	/* If you are not using Shortcodes can comment this line */
	require (TEMPLATEPATH . '/includes/shortcodes/shortcodes.php'); 


	// WIDGETS
	/* If you are not using Widgets can comment this line */
	require (TEMPLATEPATH . '/includes/widgets.php');


	// MENUS
	/* If you are not using Menus can comment this line */
	require (TEMPLATEPATH . '/includes/menus.php');


	// EXTRA
	/* All that considered as an extra or utility that is external to WordPress and not default, you should put in the "Extra" Folder */
	require (TEMPLATEPATH . '/includes/extra/content-limit.php');
	

	// ENQUEUE SCRIPTS & STYLES
	function adamantium_scripts_and_styles() {
		if ( !is_admin() ) { // this if statement will insure the following code only gets added to your wp site and not the admin page cause your code has no business in the admin page right unless that's your intentions

    		/* STYLES */
    		// Normalize stylesheet
    		wp_register_style ('normalize-stylesheet', get_stylesheet_directory_uri() . '/css/normalize.css', array(), '');
    		wp_enqueue_style ('normalize-stylesheet');

    		// IE-only stylesheet
    		wp_register_style ('adamantium-ie-stylesheet', get_stylesheet_directory_uri() . '/css/ie.css', array(), '');
    		wp_enqueue_style ('adamantium-ie-stylesheet');

    		// Main stylesheet
    		wp_register_style ('adamantium-stylesheet', get_stylesheet_directory_uri() . '/style.css', array(), '', 'all' );
    		wp_enqueue_style ('adamantium-stylesheet');
    		

    		/* SCRIPTS */
    		// Main scripts
			wp_register_script ('main-scripts', THEME_DIR . '/js/main.js', array( 'jquery' ), '1', false );
			wp_enqueue_script ('main-scripts');

			// comment reply script for threaded comments
		    if ( is_singular() AND comments_open() AND (get_option('thread_comments') == 1)) {
		      wp_enqueue_script( 'comment-reply' );
		    }
		}
	}
	add_action( 'wp_enqueue_scripts', 'adamantium_scripts_and_styles', 999)

/***************************************************************************************/
?>
<?php 
	/*
		If you want to add new things, do it from here to keep order
	*/
?>